Compute an inversion of the matrix transpose.

In [5]:
import numpy as np

In [11]:
A= ( ([1, 0.2, 0.5]), ([0.2,  1, 0.8]) , ([0.5,  0.8,  1]))
matrixA= np.array ( [[1, 0.2, 0.5], [0.2,  1, 0.8] , [0.5,  0.8,  1]])
transpose_matrixA = np.transpose(matrixA)
print("Transpose matrix:", transpose_matrixA)

Transpose matrix: [[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


Compute the determinant of the matrix

In [8]:
A= ( ([1, 0.2, 0.5]), ([0.2,  1, 0.8]) , ([0.5,  0.8,  1]))
matrixA = np.array ( [[1, 0.2, 0.5], [0.2,  1, 0.8] , [0.5,  0.8,  1]])
determinant = np.linalg.det(matrixA)
print("Determinat:", determinant)

Determinat: 0.2299999999999999


Decompose the matrix

In [1]:
import numpy as np

In [2]:
from scipy.linalg import lu

In [3]:
matrixA =np.array( ( [[1, 0.2, 0.5], [0.2,  1, 0.8] , [0.5,  0.8,  1]]))

In [7]:
P, L,U = lu(matrixA)
print(f"Original matrix:" )
print(P)
print(f"Lower Triangular matrix L:")
print(L)
print(f"Upper triangular matrix U:" )
print(U)

Original matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Lower Triangular matrix L:
[[1.         0.         0.        ]
 [0.2        1.         0.        ]
 [0.5        0.72916667 1.        ]]
Upper triangular matrix U:
[[1.         0.2        0.5       ]
 [0.         0.96       0.7       ]
 [0.         0.         0.23958333]]


Transform the matrix

In [2]:
import numpy as np
transformed_matrixA =np.transpose(matrixA)
print(transformed_matrixA)

NameError: name 'matrixA' is not defined