Compute an inversion of the matrix transpose.

In [1]:
import numpy as np

In [2]:
A= ( ([1, 0.2, 0.5]), ([0.2,  1, 0.8]) , ([0.5,  0.8,  1]))
matrixA= np.array ( [[1, 0.2, 0.5], [0.2,  1, 0.8] , [0.5,  0.8,  1]])
transpose_matrixA = np.transpose(matrixA)
print("Transpose matrix:", transpose_matrixA)

Transpose matrix: [[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [3]:
# Supply the code for the Question 2 (5 marks)
matrix = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])

matrix_transpose = matrix.T
print(f'matrix_transpose is:{matrix_transpose}')

matrix_transpose is:[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [4]:
 #Given matrix A
A = [
    [1, 0.2, 0.5],
    [0.2, 1, 0.8],
    [0.5, 0.8, 1]
]

# Transpose matrix A
A_transpose = [[row[i] for row in A] for i in range(len(A[0]))]

# Print the transposed matrix
for row in A_transpose:
    print(row)

[1, 0.2, 0.5]
[0.2, 1, 0.8]
[0.5, 0.8, 1]


Compute the determinant of the matrix

In [8]:
A= ( ([1, 0.2, 0.5]), ([0.2,  1, 0.8]) , ([0.5,  0.8,  1]))
matrixA = np.array ( [[1, 0.2, 0.5], [0.2,  1, 0.8] , [0.5,  0.8,  1]])
determinant = np.linalg.det(matrixA)
print("Determinat:", determinant)

Determinat: 0.2299999999999999


Decompose the matrix

In [1]:
import numpy as np

In [2]:
from scipy.linalg import lu

In [3]:
matrixA =np.array( ( [[1, 0.2, 0.5], [0.2,  1, 0.8] , [0.5,  0.8,  1]]))

In [7]:
P, L,U = lu(matrixA)
print(f"Original matrix:" )
print(P)
print(f"Lower Triangular matrix L:")
print(L)
print(f"Upper triangular matrix U:" )
print(U)

Original matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Lower Triangular matrix L:
[[1.         0.         0.        ]
 [0.2        1.         0.        ]
 [0.5        0.72916667 1.        ]]
Upper triangular matrix U:
[[1.         0.2        0.5       ]
 [0.         0.96       0.7       ]
 [0.         0.         0.23958333]]


Transform the matrix

In [5]:
 #Given matrix A
A = [
    [1, 0.2, 0.5],
    [0.2, 1, 0.8],
    [0.5, 0.8, 1]
]

# Define the scaling factor
scale_factor = 2

# Scale matrix A
A_scaled = [[element * scale_factor for element in row] for row in A]

# Print the scaled matrix
for row in A_scaled:
    print(row)

[2, 0.4, 1.0]
[0.4, 2, 1.6]
[1.0, 1.6, 2]
